version: '3.8'

services:
  web:
    build: ./timetablegenerator/
    ports:
      - "8000:8000"
    volumes:
      - ./timetablegenerator/:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

